# Autoformatter friendly markdownlint config (all formatting rules disabled)
default: true
blank_lines: false
bullet: false
html: false
indentation: false
line_length: false
# # MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md013.md
# MD013:
#   # Number of characters
#   line_length: 80
#   # Number of characters for headings
#   heading_line_length: 80
#   # Number of characters for code blocks
#   # code_block_line_length: 80
#   # Include code blocks
#   code_blocks: true
#   # Include tables
#   tables: true
#   # Include headings
#   headings: true
#   # Strict length checking
#   strict: false
#   # Stern length checking
#   stern: false
spaces: false
url: false
whitespace: false
no-duplicate-heading:
  siblings_only: true
